services:

  mysql:
    image: mysql/mysql-server:latest
    ports:
      - 3306:3306
    volumes:
      - ./mysql/my.cnf:/etc/my.cnf:ro
      - ./mysql/log/mysqld_slow.log:/var/log/mysql/mysqld_slow.log:rw
      #- ./mysql/log/mysql.log:/var/log/mysql/mysql.log:rw
    environment:
      - MYSQL_ROOT_PASSWORD=my_password 
    # environment:
    #   MYSQL_ROOT_PASSWORD: nimda
    #   MYSQL_DATABASE: test
    #   MYSQL_USER: admin
    #   MYSQL_PASSWORD: nimda

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.4.3
    command: filebeat -e --strict.perms=false -E output.elasticsearch.hosts=["elasticsearch:9200"] -E setup.kibana.host=kibana:5601
    user: root
    volumes:
      - ./filebeat/filebeat.yml:/etc/filebeat/filebeat.yml:ro
      #- ./mysql/log/:/usr/share/filebeat/
      - ./mysql/log/:/var/log/mysql/
  #   environment:
  #     - LOGSTASH_HOST=logstash
  #     - LOGSTASH_PORT=5044
  #     - INDEX_NAME=mysql
  #     - ENCODING="utf-8"


    #volumes:
      #Mount the filebeat configuration so users can make edit
      #- ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      #Mount the mysql logs into the filebeat container so we can access and and index them using the filebeat mysql module
      #- ./db/logs:/var/log/mysql/
      #Named volume fsdata. This is used to persist the registry file between restarts, so to avoid data duplication
      #- fbdata:/usr/share/filebeat/data/
    #command: filebeat -strict.perms=false





  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    #8.1.1
    environment:
      - cluster.name=docker-cluster
      - xpack.security.enabled=false
      - discovery.type=single-node      
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536       
    # volumes:
    #   - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      #- 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    #depends_on:
    #  - elasticsearch



